apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3sby
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3sby
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3sby
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3sby
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3sby
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-idyp-tenant/rhtap-demo-app/hacbs-test-project-3sby@sha256:c3fdfbef9953edc8a4bf5be32968d48aa2f243b8f9725f19c541c92b052f7220
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
